// llm.ts — AI replies are generated by Base44's LLM integration ("use base44").
//
// Base44's InvokeLLM is only reachable from inside a Base44 function, so the
// local backend calls the deployed functions over HTTP:
//
//   1. Preferred: the secret-guarded `llm` action on meteredChatWorker
//      (functions/meteredChatWorker.ts) — a direct, unmetered completion.
//   2. Fallback (until that action is deployed): a Base44 session the backend
//      provisions and drives to `live`, then uses its `reply` action as the
//      completion channel. Re-provisioned automatically when its meter runs out.
//
// Either way the model runs on Base44; the local backend owns the real meter.

const FUNCTION_URL = process.env.BASE44_FUNCTION_URL || '';
const WORKER_URL = process.env.BASE44_WORKER_URL || '';
const WORKER_SECRET = process.env.WORKER_SECRET || '';
const CONDUIT_ADDRESS = 'kaspa:qypcovenantsplusplusllmconduit00000000000000000';
const CONDUIT_REPLIES = 1000;

async function postJson(url: string, body: unknown): Promise<any> {
  const res = await fetch(url, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(body),
  });
  return res.json().catch(() => ({}));
}

let llmActionAvailable: boolean | null = null;
let conduitId: string | null = null;

async function provisionConduit(): Promise<string> {
  const init = await postJson(FUNCTION_URL, { action: 'init', address: CONDUIT_ADDRESS });
  const sessionId = String(init?.sessionId || '');
  if (!sessionId) throw new Error('could not provision Base44 LLM session');
  await postJson(WORKER_URL, {
    action: 'register', secret: WORKER_SECRET, sessionId,
    covenantAddress: 'kaspa:conduit', amountSompi: '0',
    epochs: 1, repliesPerEpoch: CONDUIT_REPLIES, chainJson: {},
  });
  await postJson(FUNCTION_URL, { action: 'funded', sessionId, fundingTxId: 'conduit' });
  return sessionId;
}

async function callConduit(prompt: string): Promise<string> {
  if (!conduitId) conduitId = await provisionConduit();
  let r = await postJson(FUNCTION_URL, { action: 'reply', sessionId: conduitId, message: prompt });
  if (r?.needsCheckin || /exhausted|not live/i.test(String(r?.error || ''))) {
    conduitId = await provisionConduit();
    r = await postJson(FUNCTION_URL, { action: 'reply', sessionId: conduitId, message: prompt });
  }
  if (!r?.ok) throw new Error(String(r?.error || 'Base44 LLM session failed'));
  return String(r.reply || '');
}

export async function invokeLLM(prompt: string): Promise<string> {
  if (llmActionAvailable !== false) {
    const r = await postJson(WORKER_URL, { action: 'llm', secret: WORKER_SECRET, prompt });
    if (r?.ok) { llmActionAvailable = true; return String(r.reply || ''); }
    // Action not deployed yet → fall back for the rest of this process's life.
    if (r?.error !== 'unknown_action') throw new Error(String(r?.error || 'LLM failed'));
    llmActionAvailable = false;
  }
  return callConduit(prompt);
}
